
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - relationships:
                    to: ref('my_first_dbt_model')
                    field: id


    - name: snowflake_customer_purchases
      description: "The total purchases for each customer in snowflake sample data"
      columns:
          - name: c_custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: cumulative_orders_by_date
    - name: incremental_time
    - name: playing_with_tests
      columns:
          - name: c_custkey
            tests:
                - unique
                - not_null
          - name: c_mktsegment
            tests: 
              - accepted_values:
                  values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']
